package:
  name: conda-build
  version: 1.18.2+1

source:
  git_url: ../

build:
  string: py27_esss

requirements:
  build:
    - python
  run:
    - python
    - conda
    - jinja2
    - patchelf      [linux]

test:
  commands:
    - conda-build -h
  imports:
    - conda_build

about:
  home: https://github.com/conda/conda-build
  license: BSD
